# Phase 1: Test-First Design (Red Phase)

**Purpose:** Write failing tests from acceptance criteria before implementation.

**Execution Order:** After Phase 0 (Pre-Flight Validation) completes

**Expected Outcome:** All tests RED (failing), ready for implementation

**Token Cost:** ~800 tokens in skill context (~40,000 in isolated subagent context)

---

## Overview

The Red phase is the foundation of TDD: create tests that define expected behavior before writing implementation code.

**Core Principle:** Tests document requirements and guide implementation.

---

## Phase 1: Test-First Design (Red Phase)

**Delegate test generation to test-automator subagent.**

### Step 1: Invoke test-automator Subagent

```
Task(
  subagent_type="test-automator",
  description="Generate failing tests from acceptance criteria",
  prompt="Generate comprehensive test suite for this story.

  Story content is already loaded in conversation (via @file reference from /dev command).

  Extract from story:
  1. Acceptance criteria (Given/When/Then scenarios)
  2. Technical specification (API contracts, data models, business rules)
  3. Non-functional requirements (performance, security)

  Context files available:
  - .devforgeai/context/source-tree.md (test file placement rules)
  - .devforgeai/context/coding-standards.md (test patterns, AAA format)
  - .devforgeai/context/tech-stack.md (test framework: {TEST_FRAMEWORK})

  Generate tests that:
  1. Cover all acceptance criteria
  2. Follow AAA pattern (Arrange, Act, Assert)
  3. Use test framework: {TEST_FRAMEWORK}
  4. Place tests according to source-tree.md rules
  5. Initially FAIL (Red phase of TDD)

  Test command to verify: {TEST_COMMAND}

  Return:
  - Test files created (paths and content summary)
  - Test count (unit/integration/e2e)
  - Initial test run status (all should fail)"
)
```

### Step 2: Parse Subagent Response

```javascript
result = extract_from_subagent_output(response)

tests_created = result["test_files"]
test_count = result["test_count"]

Display: "✓ Phase 1 (Red): Tests generated by test-automator"
Display: "  - Unit tests: {test_count['unit']}"
Display: "  - Integration tests: {test_count['integration']}"
Display: "  - Files created: {len(tests_created)}"

FOR file in tests_created:
    Display: "    • {file['path']}"
```

### Step 3: Verify Tests Fail (Red Phase)

```
Bash(command=TEST_COMMAND)

IF all tests fail (as expected):
    Display: "✓ RED phase confirmed - all tests failing as expected"
    Display: "  Ready for Phase 2 (Green) - implementation"

ELIF some tests pass:
    Display: "⚠️ Warning: Some tests passing unexpectedly"
    Display: "  This may indicate existing implementation or incorrect test design"
    Display: "  Proceeding to Phase 2..."

ELSE (tests not runnable):
    Display: "❌ ERROR: Tests not runnable"
    Display: "  Review test-automator output for errors"
    HALT development
```

---

## Subagents Invoked

**test-automator:**
- Generates failing tests from acceptance criteria
- Places tests according to source-tree.md
- Follows coding-standards.md test patterns
- Uses appropriate test framework from tech-stack.md

---

## Success Criteria

Phase 1 succeeds when:
- [ ] Tests generated for all acceptance criteria
- [ ] Tests follow AAA pattern (from coding-standards.md)
- [ ] Tests placed correctly (per source-tree.md)
- [ ] All tests FAIL initially (Red phase verified)
- [ ] Test command executable ({TEST_COMMAND} runs)

---

## Next Phase

**Phase 2: Implementation (Green Phase)**
- Write minimal code to make tests pass
- See `references/tdd-green-phase.md`
