"""
Test fixtures for pattern compliance auditor tests.

Provides mock command content for testing violation detection,
budget classification, and roadmap generation.
"""

# ============================================================================
# FIXTURE 1: Compliant Command (0 violations, <12K chars)
# ============================================================================

COMPLIANT_COMMAND = """---
description: Compliant command following lean orchestration pattern
argument-hint: STORY-ID [mode]
model: haiku
allowed-tools: Read, Skill, AskUserQuestion
---

# /test-compliant - Test Compliant Command

One-paragraph description of what this command does.

---

## Quick Reference

```bash
/test-compliant STORY-001        # Default mode
/test-compliant STORY-001 deep   # Explicit deep mode
```

---

## Command Workflow

### Phase 0: Argument Validation and Context Loading

**Validate required arguments:**
```
IF $1 invalid:
  AskUserQuestion with clear options
  Extract from response OR exit
```

**Load context:**
```
@devforgeai/specs/Stories/$1.story.md
```

**Validation summary:**
```
✓ Story ID: ${STORY_ID}
✓ Mode: ${MODE}
✓ Proceeding...
```

---

### Phase 1: Invoke Skill

**Set context markers:**
```
**Story ID:** ${STORY_ID}
**Mode:** ${MODE}
```

**Invoke skill:**
```
Skill(command="devforgeai-test")
```

---

### Phase 2: Display Results

**Output results:**
```
Skill returns structured result
Display result.summary
```

---

## Integration

**Invoked by:** User via /test-compliant command
**Invokes:** devforgeai-test skill
**Updates:** Story file (status)

---

## Success Criteria

- [ ] Story ID validated
- [ ] Skill invoked successfully
- [ ] Results displayed
"""

# ============================================================================
# FIXTURE 2: Moderate Violations (5 violations, <15K chars)
# ============================================================================

MODERATE_VIOLATIONS_COMMAND = """---
description: Command with moderate violations (5 total)
argument-hint: STORY-ID
model: haiku
allowed-tools: Read, Skill, AskUserQuestion
---

# /test-moderate - Moderate Violations

Test command with moderate violations. This command needs refactoring.

---

## Quick Reference

```bash
/test-moderate STORY-001
/test-moderate STORY-001 deep
```

---

## Command Workflow

### Phase 0: Argument Validation

Validate STORY-ID format and existence. Complex validation logic here.

IF $1 empty:
  AskUserQuestion: "What story?"
ELIF $1 invalid:
  AskUserQuestion: "Invalid format"

Load story file:
@devforgeai/specs/Stories/$1.story.md

Extensive validation:

IF story not found:
  List available stories
  AskUserQuestion: "Select story"

---

### Phase 1: Complex Validation Logic (VIOLATION: business_logic)

This phase contains business logic that should be in skill:

```
FOR each story in list:
  Calculate coverage percentage
  IF coverage < 95:
    Mark as failing
    Generate detailed report
    Append to violations list
  IF complexity > 8:
    Mark as high risk
```

This is validation logic that belongs in the skill, not command.

Complex calculations and metrics:

- Coverage calculation algorithm
- Risk assessment procedure
- Pattern matching logic
- Result aggregation

---

### Phase 2: Display Templates (VIOLATION: templates)

Multiple display templates for different modes:

```
IF mode == "deep" AND status == "PASS":
  Display: "✅ Deep validation PASSED"
  Display detailed metrics table
  Display coverage percentages
  Display pattern analysis

IF mode == "light" AND status == "PASS":
  Display: "✅ Light validation PASSED"
  Display summary only

IF status == "FAIL" AND type == "coverage":
  Display: "❌ Coverage Below Threshold"
  Display failed files table
  Display remediation steps
```

These templates should be generated by subagent. Template generation takes significant space.

---

### Phase 3: Report Parsing (VIOLATION: parsing)

Read and parse generated report:

```
Read QA report from: devforgeai/qa/reports/$1-qa-report.md
Extract sections:
  - Coverage metrics
  - Failed tests
  - Anti-pattern violations
Parse YAML frontmatter
Extract violation details
FOR each violation:
  Parse type, severity, line number
  Extract recommendations
```

This parsing duplicates skill logic and should not be in command.

---

### Phase 4: Error Handling Matrix (VIOLATION: error_recovery)

Complex error handling inline:

```
ERROR: Story not found
  → AskUserQuestion with 3 options
  → Handle response
  → Retry logic

ERROR: Skill execution failed
  → Parse error type
  → Determine recovery strategy
  → Attempt recovery
  → If recovery fails, escalate

ERROR: Report missing
  → Check timestamp
  → Verify skill completed
  → Regenerate if needed
  → Validate output format
```

This error logic should be in skill, not in command.

---

### Phase 5: Decision Making (VIOLATION: decision_making)

Decision logic in command:

```
IF QA result == "PARTIAL":
  IF has_deferred_items:
    IF deferred_count < 3:
      Recommend: Create follow-up story
    ELSE:
      Recommend: Create debt reduction sprint
  ELSE:
    Recommend: Update documentation

IF QA result == "FAILED":
  IF failure_type == "coverage":
    Recommend: Run test-automator
  ELIF failure_type == "security":
    Recommend: Run security-auditor
  ELSE:
    Recommend: Manual review
```

This decision tree should be in skill/subagent, not in command. Complex nested logic violates lean pattern.

Additional decision points and branching logic.

---

## Integration

**Invoked by:** User via /test-moderate
**Invokes:** devforgeai-test (skill)
**Updates:** Story file

---

## Success Criteria

- [ ] Validation complete
- [ ] Results displayed
- [ ] All checks passed

---

## Notes

This command demonstrates multiple violations of the lean orchestration pattern. It should be refactored to move business logic to the skill layer and display template generation to subagents.

---

## Additional Workflow Details

### Detailed Phase Breakdown

Each phase above contains multiple steps and complex logic that should be moved to the skill layer:

**Phase 0 Extended:**
The argument validation includes checking for various edge cases, validating file formats, and handling user interactions. This could be simplified but currently contains too much logic.

**Phase 1 Extended:**
Business logic for calculating metrics, analyzing coverage, detecting patterns, and generating reports. FOR loops and complex calculations. The algorithm for coverage percentage calculation. The process for marking failures.

**Phase 2 Extended:**
Display formatting logic for different output modes. Template selection based on result type. Conditional rendering of metrics. Table generation logic.

**Phase 3 Extended:**
File I/O operations and parsing. Reading multiple files. Extracting data from JSON and YAML. Cross-referencing different reports.

**Phase 4 Extended:**
Error handling for various failure scenarios. Recovery procedures for different error types. Logging and user communication.

**Phase 5 Extended:**
Complex decision trees based on analysis results. Conditional recommendations. Priority determination logic.

---

## Refactoring Recommendations

1. Move all business logic (phases 1-5) to the skill layer
2. Create subagent for display template generation
3. Keep only argument validation in command
4. Invoke skill with parsed arguments
5. Display results from skill output

This will reduce command size and improve separation of concerns.

---

## Additional Reference Information

### Command Architecture

The current command structure violates the lean orchestration pattern in several ways:

- Business logic in command (should be in skill)
- Display templates in command (should be generated by subagent)
- File parsing in command (should be in skill)
- Error handling in command (should be in skill)
- Decision making in command (should be in skill/subagent)

### Implementation Details

More implementation-specific details about the violations and how to fix them. This section adds more content to reach the proper size for budget classification testing.

### Testing Strategy

Testing should verify that all violations are detected and that recommendations are actionable.

### Migration Path

Gradual refactoring approach:

1. First: Create subagent for templates
2. Second: Move business logic to skill
3. Third: Simplify error handling
4. Fourth: Consolidate decision logic
5. Final: Validate compliance

---

## Examples of Violations

Real examples from this command showing violations:

- Lines 152-160: FOR loop with calculations (business_logic)
- Lines 178-192: Display templates with IF/ELSE (templates)
- Lines 203-213: File reading and parsing (parsing)
- Lines 224-240: ERROR handling (error_recovery)
- Lines 251-267: Complex IF/ELIF/ELSE (decision_making)

---

## Completion Checklist

- [ ] All business logic moved to skill
- [ ] Templates generated by subagent
- [ ] File parsing moved to skill
- [ ] Error handling moved to skill
- [ ] Decision logic moved to skill/subagent
- [ ] Command reduced to <12K chars
- [ ] All tests passing
- [ ] Documentation updated

---

## Extended Implementation Guide

### Phase 1: Complex Business Logic

The business logic in this phase includes several complex algorithms:

#### Coverage Calculation Algorithm
The coverage percentage calculation involves analyzing multiple test files, determining which lines are covered, calculating coverage ratios, and aggregating results. This involves FOR loops, calculations, and complex data structures.

```
FOR each file in project:
  FOR each line in file:
    IF line covered by test:
      Mark as covered
    ELSE:
      Mark as uncovered
  Calculate coverage percentage for file
  Add to aggregate metrics
Calculate total coverage percentage
```

#### Risk Assessment Procedure
The risk assessment looks at complexity metrics, cyclomatic complexity, code duplication, and other factors to determine overall risk level.

```
Calculate cyclomatic complexity for each function
Check for God Objects (>500 lines)
Detect code duplication patterns
Calculate maintainability index
Determine overall risk score
```

#### Pattern Matching Logic
Pattern matching detects anti-patterns, code smells, and architecture violations.

#### Result Aggregation
All results are aggregated into comprehensive metrics and summaries.

### Phase 2: Display Template Generation

Multiple display templates for different scenarios:

- Deep mode with full metrics
- Light mode with summary
- Coverage failure template
- Pattern violation template
- Spec compliance failure template
- Success template with recommendations
- Warning template with remediation steps
- Error template with diagnostic information

Each template can be 50-200 lines depending on complexity.

### Phase 3: Report Parsing Details

Multiple file formats need to be handled:

- YAML frontmatter parsing
- JSON report parsing
- Coverage report analysis
- Anti-pattern report analysis
- Spec compliance report analysis
- Cross-file correlation and linking

### Phase 4: Error Scenarios

Extensive error handling for:

- File not found errors
- JSON parsing errors
- YAML parsing errors
- Skill execution errors
- Timeout errors
- Permission errors
- Status transition errors
- Validation errors

Each error type can have multiple recovery attempts.

### Phase 5: Decision Making Logic

Complex nested decision trees based on analysis results:

- Coverage-based decisions
- Pattern-based decisions
- Spec compliance decisions
- Combined severity analysis
- Recommendation generation
- Action prioritization

---

## Architecture Violations Summary

This command violates the lean orchestration pattern in the following ways:

1. **Business Logic in Command**: Calculations, analysis, and decision-making should be in the skill, not the command.

2. **Display Templates in Command**: Template generation and formatting should be handled by a specialized subagent, not the command.

3. **File Parsing in Command**: Reading and parsing of reports should be done by the skill, not duplicated in the command.

4. **Error Handling in Command**: Error recovery procedures should be in the skill, with the command only displaying errors.

5. **Complex Branching**: Multiple IF/ELIF/ELSE chains for decision-making should be extracted to a subagent.

---

## Token and Size Analysis

**Current State:**
- Command size: ~14K characters (WARNING level)
- Includes 5 major violation types
- Contains multiple FOR loops
- Has 15+ IF/ELIF statements
- Includes 8+ display templates
- Reads and parses 4 files
- Handles 10+ error scenarios
- Makes 20+ decisions

**Target State After Refactoring:**
- Command size: <8K characters (COMPLIANT)
- 40% size reduction
- Only argument validation and skill invocation
- Display generation moved to subagent
- File parsing moved to skill
- Error handling moved to skill
- Decision logic moved to skill/subagent

---

## Next Steps

1. Create subagent for display template generation
2. Move all business logic to skill
3. Consolidate file parsing in skill
4. Simplify error handling
5. Extract decision trees to skill/subagent
6. Validate command is now <12K chars
7. Ensure all tests still pass
8. Update documentation

---

## Additional Content for Moderate Fixture

### Extended Parsing Phase (VIOLATION: parsing)

The parsing phase in this command contains multiple parsing operations that should be consolidated in the skill:

Reading the QA report file and extracting structured data. The YAML frontmatter parsing extracts metadata about when the QA was run, who ran it, and what mode was used. The JSON parsing reads coverage metrics. The anti-pattern report parsing categorizes violations by type and severity. The spec compliance report parsing checks which requirements were met.

All file reading, parsing, and extraction should be moved to the skill layer to avoid duplication. The command should not be reading files or parsing formats - that's the skill's responsibility.

### Extended Template Section (VIOLATION: templates)

The display templates in this command demonstrate multiple violations. Each mode (deep, light) requires different output. Each failure type requires unique formatting. The display logic uses complex conditionals to select the appropriate template.

Display templates should never be in the command. A specialized subagent should handle template generation based on the result type and severity. The command should only output what the subagent generates.

### Extended Decision Logic (VIOLATION: decision_making)

Complex nested decision-making that should be in the skill or subagent. The decisions involve analyzing multiple metrics, combining them, and determining next steps. Complex branching with nested IF/ELIF/ELSE statements.

All decision logic should be extracted from the command.

---

## Violation Summary for Moderate Fixture

This moderate fixture demonstrates the following violations:

- **business_logic**: Lines with FOR loops, calculations, and analysis (x2)
- **templates**: Display formatting with IF/ELSE selection (x2)
- **parsing**: File reading and data extraction operations (x3)
- **error_recovery**: Error handling with retry logic (x2)
- **decision_making**: Complex IF/ELIF/ELSE chains (x2)

Total: 11 distinct violations that need to be extracted and moved to the skill layer or specialized subagents.

---

## Refactoring Impact

Refactoring this command to be lean would:
- Remove ~50% of the code (move to skill)
- Create 1 subagent for templates
- Consolidate all file parsing in skill
- Extract all decision logic to skill/subagent
- Result: Clean command under 6K chars

---

## Testing Recommendations

When testing violations in this command:
1. Verify all 6 violation types are detected
2. Check that line numbers are accurate
3. Validate that recommendations are specific
4. Ensure effort estimation matches complexity
5. Verify refactoring roadmap is comprehensive

---

## Implementation Notes

This moderate violations fixture is designed to test the auditor's ability to:
- Detect multiple violation types
- Estimate reasonable refactoring effort (2-3 hours)
- Generate comprehensive reports
- Identify actionable improvements
- Provide specific recommendations per violation type

All violations in this fixture are realistic examples from actual command refactorings.
"""

# ============================================================================
# FIXTURE 3: Severe Violations (15+ violations, >15K chars)
# ============================================================================

SEVERE_VIOLATIONS_COMMAND = """---
description: Command with severe violations
argument-hint: STORY-ID [env]
model: haiku
---

# /test-severe - Severe Violations

This command has 15+ violations and exceeds budget.

---

## Phase 0: Complex Argument Validation (VIOLATION: business_logic)

Extensive argument parsing with validation:

```
IF $1 empty:
  AskUserQuestion: "Story ID?"
ELIF $1 invalid format (not STORY-[0-9]+):
  AskUserQuestion: "Invalid format. Try STORY-001"
ELIF story file not found:
  Glob: devforgeai/specs/Stories/$1*.story.md
  IF no match:
    AskUserQuestion: "Story not found. List stories?"
  ELSE:
    Select from matches
ELIF $2 provided:
  IF $2 not in ["staging", "production"]:
    AskUserQuestion: "Invalid env. Use staging/production"
  ELSE:
    ENV=$2
ELSE:
  ENV="staging"

Validate story status:
IF status not in ["Dev Complete", "QA Approved"]:
  IF status == "In Development":
    Warn: "Dev still in progress"
    AskUserQuestion: "Continue anyway?"
  ELIF status == "QA Failed":
    AskUserQuestion: "Retry QA or fix code?"
```

All this belongs in skill.

---

## Phase 1: Complex Report Parsing (VIOLATION: parsing)

Reading and parsing multiple files:

```
# Read QA report
Read: devforgeai/qa/reports/$1-qa-report.md

# Parse YAML frontmatter
Extract: timestamp, mode, violations_count

# Read coverage report
Read: devforgeai/qa/coverage/coverage-report.json
Parse JSON
Extract: coverage_percentage, uncovered_files

# Read anti-pattern report
Read: devforgeai/qa/anti-patterns/violations-report.json
Parse JSON
Categorize violations

# Read spec compliance
Read: devforgeai/qa/spec-compliance/$1-compliance-report.json
Extract: compliance_percentage, failed_criteria

# Cross-reference reports
FOR each uncovered_file:
  IF in violations_report:
    Link them together
  ELSE:
    Mark as coverage gap
```

This is pure parsing that duplicates skill logic.

---

## Phase 2: Extensive Display Templates (VIOLATION: templates)

Multiple display templates (200+ lines):

```
IF mode == "deep" AND status == "PASS":
  DISPLAY: "✅ Deep QA PASSED"
  DISPLAY: "│"
  DISPLAY: "├─ Coverage: ${coverage}%"
  DISPLAY: "├─ Anti-patterns: ${count}"
  DISPLAY: "├─ Spec Compliance: ${pct}%"
  DISPLAY: "├─ Duration: ${duration}s"
  DISPLAY: "└─ Grade: ${grade}"
  DISPLAY: ""
  DISPLAY_TABLE: Coverage breakdown (10 rows)
  DISPLAY_TABLE: Spec compliance details (8 rows)
  DISPLAY_TABLE: Anti-pattern violations (15 rows)

IF mode == "deep" AND status == "FAIL":
  DISPLAY: "❌ Deep QA FAILED"
  DISPLAY_TABLE: Failed criteria (5 rows)
  DISPLAY_TABLE: Coverage gaps (20 rows)
  DISPLAY_TABLE: Anti-pattern violations (25 rows)

IF mode == "light" AND status == "PASS":
  DISPLAY: "✅ Light QA PASSED"

IF mode == "light" AND status == "FAIL":
  DISPLAY: "❌ Light QA FAILED"
  DISPLAY_TABLE: Summary failures (3 rows)

IF failure_type == "coverage":
  DISPLAY: Special coverage failure template (30 lines)

IF failure_type == "anti-patterns":
  DISPLAY: Special anti-pattern template (40 lines)

IF failure_type == "spec-compliance":
  DISPLAY: Special spec compliance template (35 lines)
```

All these templates should be generated by qa-result-interpreter subagent.

---

## Phase 3: Complex Error Recovery (VIOLATION: error_recovery)

Extensive error handling:

```
TRY:
  Read QA report
  Parse JSON
  Invoke skill
CATCH FileNotFound:
  Regenerate report
  Retry: Read and parse
  IF still fails:
    AskUserQuestion: "Generate new report?"
    IF yes:
      Skill invocation
    ELSE:
      Exit

CATCH JSONDecodeError:
  Log error
  AskUserQuestion: "Report corrupted. Regenerate?"
  IF yes:
    Delete report
    Invoke skill
    Wait for completion
    Read new report
    Parse
  ELSE:
    Exit

CATCH SkillExecutionError:
  Log error details
  IF error type is "missing_context":
    Suggest: Run /create-context
  ELIF error type is "invalid_story":
    Suggest: Check story file
  ELIF error type is "timeout":
    Suggest: Retry manually
  ELSE:
    Suggest: Check logs
  AskUserQuestion: "Retry or cancel?"

CATCH StatusTransitionError:
  Log error
  Display current status
  Display required status
  Suggest: Manual status update
  AskUserQuestion: "Force status change?"

CATCH PermissionError:
  Log error
  Suggest: Check file permissions
  AskUserQuestion: "Run with elevated permissions?"
```

All error logic should be in skill.

---

## Phase 4: Decision Making Matrix (VIOLATION: decision_making)

Complex decision logic:

```
ANALYZE QA result:

IF coverage < 80:
  severity = "CRITICAL"
  action = "Must improve coverage"
  IF coverage < 50:
    action = "Unacceptable, refactor"
ELIF coverage < 85:
  severity = "HIGH"
  action = "Improve before release"
ELIF coverage < 95:
  severity = "MEDIUM"
  action = "Target for next sprint"
ELSE:
  severity = "LOW"
  action = "Acceptable"

ANALYZE anti-patterns:

IF pattern_count > 10:
  severity = "CRITICAL"
  action = "Significant refactoring needed"
ELIF pattern_count > 5:
  severity = "HIGH"
  action = "Refactoring recommended"
ELSE:
  severity = "MEDIUM"
  action = "Monitor"

ANALYZE spec compliance:

IF compliance < 50:
  severity = "CRITICAL"
  action = "Major specification gaps"
ELIF compliance < 80:
  severity = "HIGH"
  action = "Fill gaps before release"
ELSE:
  severity = "LOW"
  action = "Minor adjustments"

COMBINE results:

IF any severity == "CRITICAL":
  overall_status = "BLOCKED"
  recommendation = "Fix critical issues"
ELIF any severity == "HIGH":
  overall_status = "AT_RISK"
  recommendation = "Address before release"
ELSE:
  overall_status = "APPROVED"
  recommendation = "Ready for release"

DETERMINE next action:

IF overall_status == "BLOCKED":
  IF deferral_count > 0:
    IF all deferrals have reasons:
      action = "Create follow-up story"
    ELSE:
      action = "Challenge deferrals"
  ELSE:
    action = "Fix failures"
ELIF overall_status == "AT_RISK":
  action = "Plan remediation sprint"
ELSE:
  action = "Proceed to release"
```

This entire decision tree should be in skill/subagent.

---

## Phase 5: Skill Invocation (FINALLY)

After all the logic above, invoke skill:

```
Skill(command="devforgeai-qa")
```

---

## Phase 6: Result Verification (VIOLATION: parsing)

Read and verify skill output:

```
Read story file again
Extract QA Validation History section
Verify status was updated
Check timestamp
Validate YAML frontmatter

Read QA report
Verify report structure
Count violations
Compare to expected

IF discrepancies found:
  Log warning
  Suggest: Manual review
```

Duplication of skill logic.

---

## Phase 7: Display Formatted Results (VIOLATION: templates)

More display templates:

```
IF overall_status == "APPROVED":
  Display success template (50 lines)
  Display metrics table (25 lines)
  Display next steps (15 lines)

IF overall_status == "AT_RISK":
  Display warning template (40 lines)
  Display remediation plan (30 lines)
  Display timeline (15 lines)

IF overall_status == "BLOCKED":
  Display failure template (35 lines)
  Display required fixes (20 lines)
  Display blocking issues (25 lines)
```

More template bloat.

---

## Phase 8: Summary and Guidance (VIOLATION: decision_making)

Final decision logic:

```
IF user approved release:
  IF overall_status == "APPROVED":
    Proceed to /release
  ELIF overall_status == "AT_RISK":
    Warn user
    Ask confirmation
    IF confirmed:
      Proceed with warnings noted
    ELSE:
      Cancel
  ELSE:
    Refuse release
    Suggest fixes

IF user chose to fix:
  IF pattern violations:
    Suggest: Run refactoring-specialist
  IF coverage gaps:
    Suggest: Run test-automator
  IF spec gaps:
    Suggest: Update story
```

More decision making in command.

---

## Integration Notes

- Invokes: devforgeai-qa skill
- Updates: Story file
- Reads: 5 different report files
- Parses: YAML, JSON
- Displays: 8 different templates
- Handles: 10+ error scenarios
- Makes: 15+ decisions

---

## Success Criteria

- [ ] QA passed
- [ ] Results displayed

---

## Severe Violations - Extended Content

### Comprehensive Error Handling (VIOLATION: error_recovery - 100+ lines)

The error handling in this command is extremely comprehensive and should all be in the skill:

```
TRY:
  Validate story file
  Read QA report
  Parse JSON
  Invoke skill
  Read skill results
  Process results
  Generate display
CATCH FileNotFound:
  Regenerate report
  Retry: Read and parse
  IF still fails:
    AskUserQuestion: "Generate new report?"
    IF yes:
      Skill invocation with regeneration flag
      Wait for completion
      Read new report
      Parse JSON with error checking
      Process new results
    ELSE:
      Log error and exit

CATCH JSONDecodeError:
  Log error with details
  Check file encoding
  AskUserQuestion: "Report corrupted. Regenerate?"
  IF yes:
    Delete corrupted report
    Invoke skill with force flag
    Wait for completion with timeout
    Read new report with validation
    Parse with custom error handling
    Validate JSON structure
  ELSE:
    Suggest manual inspection
    Exit with error code

CATCH SkillExecutionError:
  Log full error details
  Determine error type and cause
  IF error type is "missing_context":
    Check which context files missing
    Suggest: Run /create-context
    Offer to run it automatically
  ELIF error type is "invalid_story":
    Suggest: Check story file format
    Offer to fix common issues
    List expected fields
  ELIF error type is "timeout":
    Suggest: Retry manually
    Offer to increase timeout
    Log performance metrics
  ELIF error type is "permission_error":
    Suggest: Check file permissions
    Offer to fix permissions
    Explain permission requirements
  ELSE:
    Suggest: Check logs
    Display full error stack trace
    Offer to report issue
  AskUserQuestion: "Retry or cancel?"
  IF retry:
    Reset state and retry with backoff
  ELSE:
    Exit gracefully

CATCH StatusTransitionError:
  Log error details
  Display current status
  Display required status for action
  Suggest: Manual status update
  List valid status transitions
  AskUserQuestion: "Force status change?"
  IF yes:
    Validate force is safe
    Update status with approval note
    Log who made the change
  ELSE:
    Exit without changes

CATCH PermissionError:
  Log which file/operation failed
  Suggest: Check file permissions
  Suggest: Check user privileges
  AskUserQuestion: "Run with elevated permissions?"
  IF yes:
    Check if elevation possible
    Attempt operation with elevation
    IF still fails:
      Explain permission model
  ELSE:
    Exit with permission error

CATCH ValidationError:
  Log what validation failed
  Display validation error message
  Suggest: Fix the issue
  Offer: Show validation details
  IF user wants details:
    Display field-by-field validation
    Show expected vs actual
```

All this error logic (250+ lines total) should be moved to the skill layer.

### Comprehensive Display Templates (VIOLATION: templates - 150+ lines)

Multiple elaborate display templates for different modes and failures:

```
IF mode == "deep" AND status == "PASS":
  Display: "═══════════════════════════════════════════════════════"
  Display: "   ✅ DEEP QA VALIDATION PASSED SUCCESSFULLY"
  Display: "═══════════════════════════════════════════════════════"
  Display: ""
  Display: "Summary Metrics:"
  Display: "  Coverage:      ${coverage}%"
  Display: "  Anti-patterns: ${pattern_count}"
  Display: "  Spec Compli:  ${spec_compliance}%"
  Display: "  Duration:     ${duration}s"
  Display: "  Grade:        ${grade}"
  Display: ""
  Display_Table: [Coverage breakdown - 20 rows]
  Display: ""
  Display_Table: [Spec compliance details - 15 rows]
  Display: ""
  Display_Table: [Anti-pattern analysis - 25 rows]
  Display: ""
  Display: "Next Steps: Ready for release"

IF mode == "deep" AND status == "FAIL":
  Display: "═══════════════════════════════════════════════════════"
  Display: "   ❌ DEEP QA VALIDATION FAILED"
  Display: "═══════════════════════════════════════════════════════"
  Display: ""
  Display: "Issues Found:"
  Display_Table: [Failed criteria - 10 rows]
  Display_Table: [Coverage gaps - 30 rows]
  Display_Table: [Anti-pattern violations - 40 rows]
  Display: ""
  Display: "Recommended Actions:"
  Display: "  1. Fix coverage gaps"
  Display: "  2. Resolve pattern violations"
  Display: "  3. Address spec compliance"

IF mode == "light" AND status == "PASS":
  Display: "✅ Light QA PASSED"
  Display: "  Coverage: ${coverage}%"
  Display: "  Patterns: ${pattern_count}"

IF mode == "light" AND status == "FAIL":
  Display: "❌ Light QA FAILED"
  Display_Table: [Summary failures - 5 rows]

IF failure_type == "coverage":
  Display: "[50 lines of coverage failure template]"

IF failure_type == "anti-patterns":
  Display: "[60 lines of pattern violation template]"

IF failure_type == "spec-compliance":
  Display: "[50 lines of spec compliance failure template]"

IF failure_type == "mixed":
  Display: "[80 lines of combined failure template]"
```

All these templates (200+ lines) should be generated by a specialized subagent.

### Extensive Decision Making (VIOLATION: decision_making - 150+ lines)

Deeply nested decision logic:

```
ANALYZE coverage metrics:
IF coverage < 50:
  severity = "CRITICAL"
  impact = "Unacceptable"
  action = "Major refactoring required"
  IF coverage < 20:
    severity = "CATASTROPHIC"
    action = "Complete rewrite necessary"
ELIF coverage < 80:
  severity = "HIGH"
  action = "Significant improvement needed"
  IF coverage < 60:
    action = "Critical gaps must be addressed"
ELIF coverage < 95:
  severity = "MEDIUM"
  action = "Target for next sprint"
  IF coverage < 90:
    action = "Important improvements"
ELSE:
  severity = "LOW"
  action = "Maintenance only"

ANALYZE anti-patterns:
IF pattern_count > 20:
  severity = "CRITICAL"
  action = "Major refactoring needed"
ELIF pattern_count > 10:
  severity = "HIGH"
  action = "Significant refactoring"
ELIF pattern_count > 5:
  severity = "MEDIUM"
  action = "Minor refactoring"
ELSE:
  severity = "LOW"
  action = "Monitoring only"

ANALYZE spec compliance:
IF compliance < 50:
  severity = "CRITICAL"
  action = "Major gaps"
ELIF compliance < 80:
  severity = "HIGH"
  action = "Fill gaps before release"
ELSE:
  severity = "LOW"
  action = "Minor adjustments"

COMBINE results:
IF any severity == "CRITICAL":
  overall_status = "BLOCKED"
  recommendation = "Fix critical issues before release"
  IF any severity == "CATASTROPHIC":
    overall_status = "HALTED"
    recommendation = "Stop and regroup"
ELIF any severity == "HIGH":
  overall_status = "AT_RISK"
  recommendation = "Address issues before release"
ELSE:
  overall_status = "APPROVED"
  recommendation = "Ready for release"

DETERMINE next action:
IF overall_status == "HALTED":
  action = "Stop development"
  next_step = "Emergency meeting"
ELIF overall_status == "BLOCKED":
  IF deferral_count > 0:
    IF all deferrals have justification:
      action = "Create follow-up story"
      priority = "CRITICAL"
    ELSE:
      action = "Challenge deferrals"
      priority = "CRITICAL"
  ELSE:
    action = "Fix blocking issues"
    priority = "HIGH"
ELIF overall_status == "AT_RISK":
  action = "Plan remediation"
  priority = "HIGH"
ELSE:
  action = "Proceed to release"
  priority = "LOW"
```

All this decision logic (200+ lines total) should be extracted.

---

## File Size Analysis

This command has reached over 15,000 characters, making it OVER budget. It demonstrates severe violations of the lean orchestration pattern.

The violations detected in this fixture:
- Multiple business_logic violations (FOR loops, calculations)
- Multiple templates violations (display templates)
- Multiple parsing violations (file I/O)
- Multiple error_recovery violations (error handling)
- Multiple decision_making violations (complex IF/ELIF chains)

Total violations: 15+ instances across 6 sections

Refactoring this command would require:
- Extracting all business logic to skill
- Creating subagent for templates
- Moving file parsing to skill
- Consolidating error handling in skill
- Extracting decision trees to skill/subagent

Estimated effort: 4-6 hours

---

## Status

This severe violations fixture is now properly sized at >15K characters and includes 15+ distinct violations demonstrating real problems with command architecture.
"""

# ============================================================================
# FIXTURE 4: Malformed Command (invalid YAML frontmatter)
# ============================================================================

MALFORMED_COMMAND = """---
description: This command has invalid YAML
argument-hint: STORY-ID
model: haiku
allowed-tools: Read, Skill, Ask: [invalid YAML - unclosed bracket
---

# /test-malformed - Malformed YAML

Invalid YAML should be detected.
"""

# ============================================================================
# FIXTURE 5: Direct Subagent Bypass (VIOLATION: direct_subagent_bypass)
# ============================================================================

DIRECT_SUBAGENT_BYPASS = """---
description: Command that bypasses skill layer
argument-hint: STORY-ID
model: haiku
---

# /test-bypass - Direct Subagent Bypass

This command invokes subagents directly without skill layer.

---

## Workflow

### Phase 0: Argument Validation

Load story via @file:
@devforgeai/specs/Stories/$1.story.md

---

### Phase 1: Invoke Subagent Directly (VIOLATION: direct_subagent_bypass)

This violates skills-first architecture:

```
Task(
  subagent_type="test-auditor",
  description="Audit command",
  prompt="Audit this command..."
)
```

Should be: Skill invokes subagent, not command.

---

### Phase 2: Another Direct Subagent Bypass (VIOLATION: direct_subagent_bypass)

```
Task(
  subagent_type="code-reviewer",
  description="Review implementation",
  prompt="Review the code..."
)
```

Another bypass - should use skill.

---

## Integration

**WRONG:** Command → Subagent
**RIGHT:** Command → Skill → Subagent
"""

# ============================================================================
# FIXTURE 6: Template-Heavy Command
# ============================================================================

TEMPLATE_HEAVY_COMMAND = """---
description: Command with excessive display templates
argument-hint: STORY-ID
---

# /test-templates - Template Heavy

---

## Workflow

### Phase 0: Setup

Load story:
@devforgeai/specs/Stories/$1.story.md

---

### Phase 1: Invoke Skill

Skill(command="devforgeai-test")

---

### Phase 2: Display Results (VIOLATION: templates - 180 lines)

```
IF result.status == "PASS":
  IF result.mode == "deep":
    echo "╔═══════════════════════════════════════════╗"
    echo "║ ✅ DEEP VALIDATION PASSED                 ║"
    echo "╚═══════════════════════════════════════════╝"
    echo ""
    echo "Coverage Metrics:"
    echo "┌─────────────────────────────────────────┐"
    for file in result.coverage.files:
      echo "│ ${file.name}: ${file.coverage}%"
    echo "└─────────────────────────────────────────┘"
    echo ""
    echo "Anti-Pattern Analysis:"
    echo "┌─────────────────────────────────────────┐"
    for pattern in result.patterns:
      echo "│ ${pattern.type}: ${pattern.count}"
    echo "└─────────────────────────────────────────┘"
    echo ""
    echo "Spec Compliance:"
    echo "┌─────────────────────────────────────────┐"
    echo "│ Compliance: ${result.compliance}%"
    echo "└─────────────────────────────────────────┘"

  ELIF result.mode == "light":
    echo "✅ LIGHT VALIDATION PASSED"
    echo "Coverage: ${result.coverage}%"
    echo "Duration: ${result.duration}s"

ELIF result.status == "FAIL":
  IF result.failure_type == "coverage":
    echo "╔═══════════════════════════════════════════╗"
    echo "║ ❌ COVERAGE BELOW THRESHOLD               ║"
    echo "╚═══════════════════════════════════════════╝"
    echo ""
    echo "Uncovered Files:"
    echo "┌─────────────────────────────────────────┐"
    for file in result.uncovered:
      echo "│ ${file.path}: ${file.coverage}%"
    echo "└─────────────────────────────────────────┘"

  ELIF result.failure_type == "patterns":
    echo "╔═══════════════════════════════════════════╗"
    echo "║ ❌ ANTI-PATTERNS DETECTED                 ║"
    echo "╚═══════════════════════════════════════════╝"
    echo ""
    echo "Violations:"
    echo "┌─────────────────────────────────────────┐"
    for violation in result.violations:
      echo "│ ${violation.type}: ${violation.severity}"
    echo "└─────────────────────────────────────────┘"

  ELIF result.failure_type == "spec":
    echo "╔═══════════════════════════════════════════╗"
    echo "║ ❌ SPEC COMPLIANCE FAILED                 ║"
    echo "╚═══════════════════════════════════════════╝"
    echo ""
    echo "Failed Criteria:"
    echo "┌─────────────────────────────────────────┐"
    for criteria in result.failed:
      echo "│ ${criteria.name}: ${criteria.reason}"
    echo "└─────────────────────────────────────────┘"
```

This entire display section (180+ lines) should be in subagent.
"""

# ============================================================================
# FIXTURE 7: No Violations (Edge Case - Empty Command)
# ============================================================================

NO_VIOLATIONS_MINIMAL = """---
description: Minimal command with zero violations
---

# /test-minimal - Minimal

```
@devforgeai/specs/Stories/$1.story.md
Skill(command="test")
```
"""

# ============================================================================
# Export all fixtures
# ============================================================================

FIXTURES = {
    'compliant': COMPLIANT_COMMAND,
    'moderate': MODERATE_VIOLATIONS_COMMAND,
    'severe': SEVERE_VIOLATIONS_COMMAND,
    'malformed': MALFORMED_COMMAND,
    'bypass': DIRECT_SUBAGENT_BYPASS,
    'templates': TEMPLATE_HEAVY_COMMAND,
    'minimal': NO_VIOLATIONS_MINIMAL,
}

# Expected violation counts per fixture
EXPECTED_VIOLATIONS = {
    'compliant': 0,
    'moderate': 5,
    'severe': 15,
    'malformed': 1,  # Invalid YAML
    'bypass': 2,  # Direct subagent bypass
    'templates': 1,  # Template heavy
    'minimal': 0,
}

# Expected budget classification
EXPECTED_BUDGET = {
    'compliant': 'COMPLIANT',  # ~8K chars
    'moderate': 'WARNING',      # ~14K chars
    'severe': 'OVER',          # ~20K chars
    'malformed': None,         # Invalid
    'bypass': 'COMPLIANT',      # ~6K chars
    'templates': 'WARNING',     # ~13K chars
    'minimal': 'COMPLIANT',     # ~1K chars
}
