"""
ConfigurationInitializer - ast-grep configuration directory structure setup.

Handles creation of .devforgeai/ast-grep/ directory structure
and sgconfig.yml generation for STORY-116.
"""

import logging
from pathlib import Path
from typing import List, Optional, NamedTuple
from datetime import datetime

try:
    import yaml
except ImportError:
    yaml = None

logger = logging.getLogger(__name__)


class InitResult(NamedTuple):
    """Result of initialization operation."""
    success: bool
    created_paths: List[Path]
    config_path: Path
    error: Optional[str] = None


class ConfigurationInitializer:
    """
    Initializes ast-grep configuration directory structure.

    Creates:
    - .devforgeai/ast-grep/ root directory
    - sgconfig.yml configuration file
    - rules/python/, rules/csharp/, rules/typescript/, rules/javascript/ directories

    Implements SVC-001, SVC-002, SVC-003, BR-002 requirements.
    """

    DEFAULT_LANGUAGES = ["python", "csharp", "typescript", "javascript"]

    def __init__(self, project_root: Path):
        """
        Initialize with project root directory.

        Args:
            project_root: Project root directory path
        """
        self.project_root = Path(project_root)
        self.ast_grep_dir = self.project_root / ".devforgeai" / "ast-grep"

    def initialize(self, force: bool = False) -> InitResult:
        """
        Create ast-grep configuration directory structure.

        Args:
            force: If True, overwrite existing configuration (default: False)

        Returns:
            InitResult with success status and details

        Implements:
            SVC-001: Create directory structure
            SVC-002: Generate sgconfig.yml with defaults
            SVC-003: Skip existing without overwriting (unless force=True)
            BR-002: sgconfig.yml not overwritten unless force=True
        """
        created_paths: List[Path] = []

        try:
            # Check PyYAML availability
            if yaml is None:
                return InitResult(
                    success=False,
                    created_paths=created_paths,
                    config_path=self.ast_grep_dir / "sgconfig.yml",
                    error="PyYAML is required for configuration generation",
                )

            # SVC-001: Create .devforgeai/ast-grep/ directory
            self.ast_grep_dir.mkdir(parents=True, exist_ok=True)
            created_paths.append(self.ast_grep_dir)

            # SVC-001: Create rules subdirectories
            rules_dir = self.ast_grep_dir / "rules"
            for lang in self.DEFAULT_LANGUAGES:
                lang_dir = rules_dir / lang
                lang_dir.mkdir(parents=True, exist_ok=True)
                created_paths.append(lang_dir)

            # SVC-002, SVC-003, BR-002: Handle sgconfig.yml
            config_path = self.ast_grep_dir / "sgconfig.yml"

            if config_path.exists() and not force:
                # SVC-003, BR-002: Skip existing config without force flag
                logger.info(f"Skipped existing config: {config_path} (use --force to overwrite)")
                return InitResult(
                    success=True,
                    created_paths=created_paths,
                    config_path=config_path,
                    error=None,
                )

            # SVC-002: Generate default sgconfig.yml
            self._write_default_config(config_path)

            return InitResult(
                success=True,
                created_paths=created_paths,
                config_path=config_path,
                error=None,
            )

        except PermissionError as e:
            return InitResult(
                success=False,
                created_paths=created_paths,
                config_path=self.ast_grep_dir / "sgconfig.yml",
                error=f"Permission denied: {e}",
            )
        except Exception as e:
            return InitResult(
                success=False,
                created_paths=created_paths,
                config_path=self.ast_grep_dir / "sgconfig.yml",
                error=f"Initialization failed: {e}",
            )

    def _write_default_config(self, config_path: Path) -> None:
        """Write default sgconfig.yml configuration."""
        config = self._generate_default_config()

        header = "# DevForgeAI ast-grep Configuration\n# Generated by: devforgeai ast-grep init\n\n"

        with open(config_path, 'w', encoding='utf-8') as f:
            f.write(header)
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    def _generate_default_config(self) -> dict:
        """Generate default sgconfig.yml configuration."""
        return {
            'ruleDirs': [f"rules/{lang}" for lang in self.DEFAULT_LANGUAGES],
            'languageGlobs': {
                'python': '**/*.py',
                'csharp': '**/*.cs',
                'typescript': '**/*.ts',
                'javascript': '**/*.js',
            },
            'testDirs': ['tests', '__tests__'],
            'devforgeai': {
                'version': '1.0',
                'created': datetime.now().strftime('%Y-%m-%d'),
            }
        }

    def is_initialized(self) -> bool:
        """Check if configuration is already initialized."""
        config_path = self.ast_grep_dir / "sgconfig.yml"
        rules_dir = self.ast_grep_dir / "rules"

        return (
            config_path.exists()
            and rules_dir.exists()
            and all((rules_dir / lang).exists() for lang in self.DEFAULT_LANGUAGES)
        )
