"""Audit-owned report reduction. No imported package verdicts or validator tools."""
import datetime
import json
from pathlib import Path
import re
from capture import RUN, ROOT, sha

DIGEST='338c70995e72637e0ce84991be110d6a371ab6965faf4009d570156ea0e13cf2'
def save(name,value):
    (RUN/name).write_text(value if isinstance(value,str) else json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def read(name):return json.loads((RUN/name).read_text(encoding='utf-8'))

FINDINGS=[
 {'id':'F-01','severity':'HIGH','category':'implementation defect','requirements':['BA-005','BA-006','BA-014'],'cases':['BAT-08','BAT-10'],'clause':'5.1, 5.3, 9: closed legacy records and exact member custody/request bindings','source':'scripts/adaptive.py:389-400,435-449','expected':'Reject malformed referenced authoring/request records and requests whose target identity or manifest disagrees with the delivered member.','actual':'inspect returned VALID/exit 0 separately for PASS quality statuses, wrong record_kind, wrong request target name/root, boolean changed_paths, and an empty unrelated target_manifest, after all reference hashes and publication references were refreshed.','reproduction':['ext2-linked-quality','ext2-linked-kind','ext2-linked-request-identity','ext2-linked-request-type','ext2-linked-request-manifest'],'impact':'The set packet can appear custody-valid while carrying invalid quality claims and a request for another target. No protected authority bypass is claimed.','confidence':'HIGH','correction':'Validate every legacy field against its unchanged family schema and cross-bind target name/root, manifest rows/digest, run identity and changed paths to actual publication. Preserve legacy version semantics.','counterevidence':'The valid control is accepted; correct partial/subset packets and false-full/omission negatives behaved correctly. This is not a claim that the normal publisher fabricates these fields.'},
 {'id':'F-02','severity':'MEDIUM','category':'implementation defect, inherited from preserved baseline','requirements':['BA-005','BA-011'],'cases':['BAT-08','BAT-09'],'clause':'5.1 and 9: preserve closed legacy schemas and actual parser behavior','source':'scripts/authoring.py:241-247; schemas/authoring-contract.schema.json:113','expected':'An unlisted top-level authoring-contract-v1 field is rejected before staging.','actual':'begin accepted unlisted_field: true and returned STAGED/exit 0. The shipped schema has additionalProperties: false; begin only checks the required-key subset.','reproduction':['v2-author-extra-contract-field'],'impact':'Unsupported contract fields can enter custody evidence instead of failing closed. Valid arbitrary objects inside the legacy requirements array remain supported and must stay supported.','confidence':'HIGH','correction':'Enforce the closed top-level schema and declared optional fields without tightening legacy requirement object contents.','counterevidence':'Duplicate-key parsing and selected required-field/type checks exist. Historical byte comparison confirms this helper was preserved, so this is not newly introduced by adaptation.'},
 {'id':'F-03','severity':'HIGH','category':'implementation defect','requirements':['BA-002','BA-009'],'cases':['BAT-07','BAT-15'],'clause':'4.2 exclusions and 6.2 refusal of excluded files in exact runtime capture','source':'assets/adaptive-runtime/check_project_binding.py:110-111,142-157','expected':'Reject recognized private-key/certificate-container filenames before reading/hashing; do not return MATCH for a package containing excluded key material.','actual':'Synthetic id_rsa and identity.pfx package files were inventoried and returned MATCH/BOUND on both Windows and Linux. Only a small suffix list is checked.','reproduction':['windows-private-key-name','windows-pfx-name','linux-private-key-name','linux-pfx-name'],'impact':'The helper reads/hashes files the selected contract excludes, and can bind such a package as complete. No real credentials were used or exposed.','confidence':'HIGH','correction':'Define and share a complete conservative private-key exclusion policy (including standard private-key basenames and credential containers), apply it before file reads, and retain explicit omission/rejection reasons.','counterevidence':'node_modules and symlink/junction negatives were rejected; .pem and .key suffixes are already rejected. Stdout did not expose a UUID or file contents.'},
 {'id':'F-04','severity':'HIGH','category':'implementation defect, inherited from preserved baseline','requirements':['BA-011'],'cases':['BAT-11','BAT-17'],'clause':'1.1 and 9 preserved legacy identity; known conflicting history blocks','source':'scripts/authoring.py:221-238; scripts/custody.py:367-379','expected':'A selected schema-2 adoption pointer must identify the same skill and run as its adopted origin.','actual':'begin accepted a pointer with target_name wrong-skill and run_id wrong-run while its origin describes sample/old1. It returned STAGED/exit 0. The adopted record and baseline checks passed but pointer identity was never checked.','reproduction':['ext2-legacy-wrong-pointer'],'impact':'Conflicting known custody history can establish an edit base. The existing custody.pointer_record check is not called on this source-to-effect branch.','confidence':'HIGH','correction':'Validate the entire selected pointer and bind its run/name/origin/baseline to the adopted record before beginning an edit; preserve old bytes and fail conflicting history.','counterevidence':'Independently constructed valid generated/adopted histories staged successfully; corrupt generated baseline bytes were rejected.'}
]

# Explicit compound-case ledger: an executed helper observation never substitutes for a cold workflow.
SUBCASES={
1:[('ordinary helper create/edit and exact manual request','PASS','v2-author-create-publish, v2-author-edit-publish; followup-results.json'),('cold ordinary create and focused edit with no quality process','NOT_RUN','cold-create-01 host failure; cold-create-02 timeout before delivery; edit dependent on complete create')],
2:[('junction/link refusal by runtime helper','PASS','windows-symlink, linux-symlink'),('monorepo facts, unknown manifest, exclusions, no project execution and citations in completed proposal','NOT_RUN','cold-propose-typescript timed out; raw inputs preserved'),('default discovery aggregate budgets and secret exclusions in autonomous discovery','NOT_RUN','No completed bounded discovery result')],
3:[('Windows independent count and byte capture ceiling and exact boundary values','PASS','binding-file-limit, binding-byte-limit, windows-exact-files, windows-over-files, windows-exact-bytes, windows-over-bytes'),('Linux byte ceilings','PASS','linux-exact-bytes, linux-over-bytes'),('Linux count ceilings','NOT_RUN','linux-exact-files and linux-over-files timed out at 120 seconds on /mnt/c; no output'),('missing Python isolated child and required unavailable Rust capability preflight','PASS','missing-python-child, selection-missing-capability'),('independent prose retained and dependent authoring blocked after unavailable capability; shared-original discovery accounting','NOT_RUN','No cold capability-failure proposal or explicit shared-original boundary fixture')],
4:[('HTTP retained and storage justified with actual supporting sources','NOT_RUN','Cold TypeScript/domain fixture included existing HTTP skill; proposal not completed')],
5:[('three-parent full inventory, missing row, unauthorized removal linkage; LF/CRLF and older Markdown resource','PASS','lineage-fence-lf, lineage-fence-crlf, lineage-table-other-resource and associated negatives'),('semantic equivalence and real current authorization adjudication in authored variant','NOT_RUN','Helpers check shape/linkage; no completed cold variant/removal case')],
6:[('portable template and source identity review, synthetic relocation','PASS','source-text-inventory.json; windows-relocated, linux-relocated; generated fixture copies generic helper'),('cold adaptive authoring and relocated package completion','NOT_RUN','No completed native adaptive authoring; scripted C publication is separate evidence')],
7:[('correct/missing/root/inactive/changed/duplicate/role/unbound/unknown-version/descriptor/core-variant/two-variant results','PASS','binding-* ordinary matrix; initial-suite-results.json'),('excluded private-key filenames rejected','FAIL','F-03'),('no UUID output, no helper writes, unsafe junctions and POSIX I/O failure','PASS','binding-* effects; windows-symlink, linux-symlink, linux-io-error'),('actual generated-skill no-product-write/no-downstream behavior on rejection and resume','NOT_RUN','Independent controller and read-only helper do not prove agent enforcement')],
8:[('new evidence/proposal/selection/descriptor/set shapes; duplicate keys/nonfinite/extra fields/invalid IDs/stale refs/locator bounds','PASS','record-*, proposal-*, selection-*, descriptor-valid; ordinary positives and negatives'),('strict linked legacy records and target bindings','FAIL','F-01, F-02'),('all new record families complete positive/negative semantic cross-reference grid','NOT_RUN','No exhaustive per-field matrix for project-binding/adaptive-observation/binding-observation inspect dispatch, or every misleading citation')],
9:[('legacy schema bytes unchanged; valid arbitrary legacy requirement objects and manual requests','PASS','legacy-byte-comparison.json; v2-author-*; author-request-readback'),('closed legacy top-level interpretation','FAIL','F-02; F-01 linked reader')],
10:[('A occupied preflight, B blocked, real C publication; PARTIAL and eligible subset omissions','PASS','v2-set-A-preflight-fails, v2-set-C-publish, v2-set-partial-result-valid, v2-set-subset-valid and omission negatives'),('exact linked per-member custody','FAIL','F-01'),('autonomous continuation, all retained/full-set/handoff omission permutations and interrupted C writes','NOT_RUN','Auditor scripted controller; no new cold set trial or complete fault-injection/full-set grid')],
11:[('cycles, missing/unselected dependency, occupied destination, user-edited obsolete file, divergent B/C/N, shared input stale ref','PASS','proposal-cycle, selection-*, v2-bcn-*, record-stale-reference'),('conflicting known adoption pointer identity','FAIL','F-04'),('concurrent drift no overwrite','PASS','v2-author-drift-publish retains changed user.txt with applied_paths empty; status ambiguity D-01'),('destination ancestor overlaps, unowned collision, per-path interruption and all handoff-cycle variants','NOT_RUN','Source branches reviewed; no complete fresh executed grid')],
12:[('description semantic classification and progressive routing','PASS','source-review.md routing table; description-only manual analysis'),('completed native mode invocation/implicit selection and handoff stopping','NOT_RUN','All applicable cold attempts timed out; implicit activation not executed')],
13:[('unchanged/equivalent-byte-changed review, false NO_CHANGE rejection and missing parent reference','PASS','ext2-update-*'),('materially removed core requirement and native revision-impact proposal','NOT_RUN','No completed cold update review; no executed material-removal proposal')],
14:[('all four convention fixtures specified and cold attempts retained','PASS','proposal_trials.py; cold-propose-*-plan.json'),('completed four-project adaptation and contradictory same-scope convention','NOT_RUN','All four proposals timed out; ambiguous-convention cold variant not run')],
15:[('Windows/POSIX hostile paths and offline standard-library helper; isolated missing executable','PASS','binding-hostile-path, windows-valid, linux-valid, missing-python-child; source call review'),('private-key exclusion in portable helper','FAIL','F-03'),('cold missing-interpreter reporting and OS network isolation qualification','NOT_RUN','Only child launch failure and source-local network-free execution observed')],
16:[('stale input digest rejection','PASS','record-stale-reference; ext2-update-missing-history'),('native resume with changed original evidence and fresh linked proposal; runtime match invalidation','NOT_RUN','No native resume trial; instructions reviewed, no cached-authority claim credited')],
17:[('ordinary import/spec-build, observed edit, authored baseline, explicit new adoption, legacy generated/adopted baseline, corrupt baseline','PASS','v2-author-*; ext2-legacy-generated, ext2-legacy-adopted, ext2-legacy-corrupt-generated'),('wrong known legacy pointer','FAIL','F-04'),('complete Claude conversion dispositions and schema-2 generated-after-adoption lineage/retry histories','NOT_RUN','Import helper operation is not a complete semantic conversion or all legacy ancestry modes')]
}

def main():
    save('findings.json',FINDINGS)
    ledger=['# Findings ledger','',f'Target digest: `{DIGEST}`. No corrections applied.','']
    for f in FINDINGS:
        ledger += [f"## {f['id']} — {f['severity']} — {f['category']}",'',f"Source: `src/agents/skills/skill-builder/{f['source']}`. Clauses: {f['clause']}. {', '.join(f['requirements']+f['cases'])}.",'',f"Expected: {f['expected']}",'',f"Actual: {f['actual']}",'',f"Minimal reproductions: {', '.join('`commands/'+c+'/command.json`' for c in f['reproduction'])}. Each directory preserves stdout, stderr and exit; corresponding independently constructed input paths are in the argv. Execute a fresh copy for mutating begin cases.",'',f"Impact: {f['impact']}",f"Confidence: {f['confidence']}. Counterevidence: {f['counterevidence']}",'',f"Proposed correction: {f['correction']}",'']
    ledger+=['## D-01 — LOW — status/contract ambiguity','', '`authoring.py:409-417` reports PARTIAL when a concurrent actor changes user.txt before the first builder write, even though applied_paths is empty. v2-author-drift-publish retains the external edit and stops. This is not an overwrite defect. Clarify whether PARTIAL means builder-applied effects or any observed live delta, and distinguish the actor in the receipt. This observation is not counted as a confirmed implementation defect.','', '## E-01 — audit evidence limitations','', 'Initial second-edit/B/C/N fixtures had an invalid run-root layout; their setup errors are not valid defect reproductions. Fresh followup fixtures corrected the harness only. The first coverage wrapper altered Python import semantics; its ModuleNotFoundError observations are instrumentation failures, not builder defects. The fresh coverage driver restores direct-script imports. All attempts remain. Timeout rows are NOT_RUN, including Linux count-limit commands.','', 'Some initial commands retained argv/oracle/raw output but lacked an explicit per-case pre-execution input manifest and complete effect inventory. Fixture source and in-place inputs support reproduction, but this does not meet the entire requested receipt contract for those cases. No retrospective hash is labeled as a pre-execution hash. Cold execution inherited host context, including a memory lookup in cold-create-02; it is an explicit child task, not fully held-out context or implicit-discovery proof.','']
    save('findings-ledger.md','\n'.join(ledger))
    bat=[]
    for number,subs in SUBCASES.items():
        for n,(name,status,evidence) in enumerate(subs,1):bat.append({'id':f'BAT-{number:02d}.{n:02d}','parent':f'BAT-{number:02d}','required_behavior':name,'status':status,'method':'native/helper/static/semantic as expressly identified in evidence','evidence':evidence,'target_digest':DIGEST})
    def reduce(values):return 'FAIL' if 'FAIL' in values else 'NOT_RUN' if 'NOT_RUN' in values else 'PASS'
    bat_status={f'BAT-{n:02d}':reduce([x[1] for x in subs]) for n,subs in SUBCASES.items()}
    spec=(RUN/'inputs/skill-builder-adaptive-enhancement-spec.md').read_text(encoding='utf-8').splitlines()
    ba=[]
    for line in spec:
        if line.startswith('| BA-'):
            cells=[c.strip() for c in line.strip('|').split('|')];cases=re.findall(r'BAT-\d+',cells[2]);ba.append({'id':cells[0],'requirement':cells[1],'cases':cases,'status':reduce([bat_status[c] for c in cases]),'target_digest':DIGEST})
    save('bat-traceability.json',bat);save('requirement-traceability.json',ba)
    md=['# Requirement and BAT traceability','',f'Target `{DIGEST}`. PASS below applies only to the named observation. A parent requirement passes only if all required subcases do. NOT_RUN is incomplete, not a pass.','', '| Requirement | Status | Required behavior | BAT mapping |','|---|---|---|---|']
    md += [f"| {r['id']} | {r['status']} | {r['requirement']} | {', '.join(r['cases'])} |" for r in ba]
    md+=['','| Subcase | Status | Independent oracle / required behavior | Evidence and limitation |','|---|---|---|---|']
    md += [f"| {r['id']} | {r['status']} | {r['required_behavior']} | {r['evidence']} |" for r in bat]
    save('traceability-matrix.md','\n'.join(md)+'\n')
    # Retain every complete-spec paragraph/table row, including non-register obligations.
    clause=[];start=None;buf=[]
    def flush(end):
        nonlocal start,buf
        if not buf:return
        text=' '.join(buf);line=start
        if line<41:src='SKILL.md:7-24; references/adaptation.md:3-17';cases=['BAT-01','BAT-04','BAT-06','BAT-17']
        elif line<84:src='references/adaptation.md:7-21; SKILL.md:11-24';cases=['BAT-02','BAT-03','BAT-04','BAT-12']
        elif line<134:src='scripts/adaptive.py:29-351; schemas/adaptive-common.schema.json; references/adaptive-contracts.md:3-31';cases=['BAT-05','BAT-08','BAT-09']
        elif line<157:src='scripts/adaptive.py:353-476; references/adaptation.md:21-38; scripts/authoring.py:241-455';cases=['BAT-10','BAT-11']
        elif line<173:src='assets/adaptive-runtime/check_project_binding.py:172-214; scripts/adaptive.py:242-257; references/adaptive-contracts.md:29-39';cases=['BAT-05','BAT-06','BAT-08']
        elif line<210:src='assets/adaptive-runtime/check_project_binding.py:211-296; references/project-binding.md:5-33';cases=['BAT-07','BAT-15','BAT-16']
        elif line<218:src='references/adaptation.md:40-44; scripts/adaptive.py:273-351';cases=['BAT-13','BAT-16']
        elif line<261:src='All source locators above; traceability-matrix.md';cases=[f'BAT-{n:02d}' for n in range(1,18)]
        else:src='SKILL.md; scripts/adaptive.py:485-518; references/evidence-format.md; legacy-byte-comparison.json';cases=['BAT-08','BAT-09','BAT-12','BAT-17']
        clause.append({'id':f'SPEC-L{start:03d}-L{end:03d}','spec_start_line':start,'spec_end_line':end,'text':text,'source_locations':src,'cases':cases,'status':reduce([bat_status[x] for x in cases]),'method':'Complete source/contract review plus specified BAT observations; unresolved compound behavior remains NOT_RUN under FAIL precedence','evidence':'traceability-matrix.md; source-review.md; findings-ledger.md','target_digest':DIGEST})
        start=None;buf=[]
    for i,line in enumerate(spec,1):
        if not line.strip():flush(i-1)
        elif line.startswith('|') or line.startswith('- '):
            flush(i-1);start=i;buf=[line];flush(i)
        else:
            if start is None:start=i
            buf.append(line)
    flush(len(spec))
    save('complete-spec-traceability.json',clause)
    save('complete-spec-traceability.md','# Complete specification coverage ledger\n\nEvery nonblank paragraph and table row is retained, including interface fields and obligations outside BA-001–014. Status is conservative at the mapped workflow group, not a claim that every clause in a failed group is defective. Exact defects are in the findings ledger.\n\n| Clause | Status | Source locations | BAT mapping |\n|---|---|---|---|\n'+'\n'.join(f"| {r['id']} | {r['status']} | {r['source_locations']} | {', '.join(r['cases'])} |" for r in clause)+'\n')
    commands=[]
    for d in sorted((RUN/'commands').iterdir()):
        if not d.is_dir() or not (d/'command.json').exists():continue
        command=json.loads((d/'command.json').read_text(encoding='utf-8'));result=json.loads((d/'result.json').read_text(encoding='utf-8')) if (d/'result.json').exists() else {'exit':None,'timeout':None};commands.append({'id':d.name,'command':command,'result':result})
    save('command-log.json',commands)
    save('command-log.md','# Exact command log\n\nArguments are serialized arrays; no shell reconstruction is needed. Each commands/<id>/ directory retains the original command/oracle, stdin when present, stdout, stderr and result. Tool-based bootstrap source reads and approvals remain in the conversation; they were not all independently transcribed before execution, as disclosed in E-01.\n\n'+'\n'.join(f"## {c['id']}\n\n```json\n{json.dumps(c['command'],ensure_ascii=False,indent=2)}\n```\n\nExit: {c['result']['exit']}; timeout: {c['result']['timeout']}. Raw output: `commands/{c['id']}/stdout.txt`, `stderr.txt`.\n" for c in commands))
    coverage=read('coverage.json')['totals'];line_pct=100*coverage['covered_lines']/coverage['num_statements'];branch_pct=100*coverage['covered_branches']/coverage['num_branches']
    native=[c for c in commands if c['id'].startswith('cold-')]
    counts={s:sum(v==s for v in bat_status.values()) for s in ('PASS','FAIL','NOT_RUN')};subcounts={s:sum(r['status']==s for r in bat) for s in ('PASS','FAIL','NOT_RUN')}
    save('coverage-reduction.json',{'BAT':bat_status,'BAT_counts':counts,'subcase_counts':subcounts,'required_case_pass_rate':100*counts['PASS']/17,'executed_line_coverage':line_pct,'branch_coverage':branch_pct,'coverage_raw':coverage,'scope':'Only instrumented supplemental Windows cases; earlier uninstrumented observations not included. Native Linux line coverage NOT_RUN. No retries counted as additional required BAT cases.'})
    report=f'''# Independent QA audit: FAIL, with incomplete coverage

This exact development-source skill-builder does **not** meet the complete selected acceptance contract. Four confirmed implementation defects are demonstrated by independent positive/negative fixtures. Required native workflows and several compound subcases remain unverified. Audit reporting is complete; skill acceptance is not granted.

Target: `C:/Projects/DevForgeAI/src/agents/skills/skill-builder`\n
Package SHA-256: `{DIGEST}` (43 files, 276,781 bytes). Both supplied specification hashes matched. Current bytes match the historical delivered receipt. The independently recomputed pre-enhancement snapshot digest also matched; 26 old files, including all legacy helpers/schemas, are unchanged, two changed and 15 were added. F-02/F-04 are inherited defects rather than demonstrated adaptive regressions.

## Consequential findings

1. **F-01:** The set reader accepts invalid linked authoring/request fields, fabricated quality statuses, and requests with the wrong target or manifest.
2. **F-03:** Both native OS helpers return MATCH for packages containing excluded synthetic private-key filenames.
3. **F-04:** Legacy adoption intake accepts a selected pointer naming another skill and run.
4. **F-02:** Authoring intake accepts unlisted fields despite its closed legacy contract.

See [findings-ledger.md](findings-ledger.md) for exact source locators, expected/actual behavior, individual reproductions, counterevidence, impact and proposed corrections. No repairs were applied. D-01 separately records the ambiguous PARTIAL label after an external concurrent edit.

## Executed observations and limits

Ordinary helper create/edit/import/spec-build/adopt, exact manual requests, B/C/N retention/conflicts, parent requirement inventories with LF/CRLF and alternate resources, topological selection, real per-member C publication, partial/eligible-subset envelopes, update-review equality/stale checks, metadata preservation and initializer/spec lookup branches were exercised independently. Static review decoded all 43 files, parsed all Python/JSON, checked the package's own artifact hashes and found no missing local Markdown link target.

Windows and native Ubuntu/Python helper executions covered binding outcomes, hostile argv paths, junction/symlink refusal and capture boundaries. Linux I/O denial passed. Linux exact/over-count cases timed out at 120 seconds on the Windows-mounted evidence path; they are NOT_RUN, not product FAIL. Synthetic credential fixture values and UUIDs stay in their disposable operational scope; UUIDs were absent from helper output. A read-only helper/controller does not establish a generated skill's suppression of product effects.

Cold CLI: installed `codex-cli 0.154.0`, existing gpt-6-astra configuration, normal workspace-write/ephemeral child invocation, no bypass flags or configuration edits. One initial create attempt failed host app-server permissions; the approved fresh create reached custody staging then timed out. All four fresh convention proposals also timed out at 120 seconds. No completed native PASS, implicit discovery PASS, autonomous set orchestration, adaptive runtime product-write gate or resume behavior is claimed. Child context was not fully held out (see E-01).

All **14 BA requirements**, **17 BAT parents**, **{len(bat)} explicit compound observations**, and **{len(clause)} complete-spec paragraph/table entries** are mapped in [traceability-matrix.md](traceability-matrix.md) and [complete-spec-traceability.json](complete-spec-traceability.json). BAT parent outcomes: {counts['PASS']} PASS, {counts['FAIL']} FAIL, {counts['NOT_RUN']} NOT_RUN. Compound observations: {subcounts['PASS']} PASS, {subcounts['FAIL']} FAIL, {subcounts['NOT_RUN']} NOT_RUN. Parent required-case pass rate is {100*counts['PASS']/17:.2f}% (passing complete BAT cases / 17); helper subchecks and retries cannot inflate it.

Supplemental measured Windows line coverage: **{coverage['covered_lines']}/{coverage['num_statements']} = {line_pct:.2f}%**; branch coverage: **{coverage['covered_branches']}/{coverage['num_branches']} = {branch_pct:.2f}%**. Denominator is all seven first-party Python files, no excluded executable lines. This partial instrumented campaign is below 95%; earlier uninstrumented runs cannot be retroactively counted. Linux line coverage and compiled-Rust framework qualification are NOT_RUN. The measured pass/coverage floors do not grant acceptance, and both required 95% floors remain unmet in this declared audit coverage.

The audit retained harness layout and instrumentation failures, then used fresh corrected fixtures. Those setup errors are not implementation defects or valid red tests. Some initial cases lack the full requested pre-execution digest/effect receipt, which is an explicit audit evidence gap rather than retrospective proof. Raw attempts, commands, fixtures, output and coverage data remain in this run.

## Work still required

Correct F-01 through F-04 in a separately authorized development task, then independently rerun positive and negative cases. Complete cold create/edit, monorepo and four-convention proposals (including contradictory same-scope instructions), storage/HTTP preservation, authorized/unauthorized variant dispositions, autonomous A/B/C continuation, material core update, changed-input resume, and generated-skill non-MATCH/no-product-effects trials. Complete the legacy generated-after-adoption/history and full-set/handoff/fault-interruption grids. Rerun Linux count limits on an authorized native filesystem with the same timeout, and obtain complete pre/post receipts and >=95% required suite pass rate/line coverage without excluding uncovered behavior.

Builder-to-validator execution is explicitly outside this audit. The prior compatibility report was examined only after independent planning/review, and its validator verdicts were not used as an oracle. No validator package, grader or test was loaded/executed. No operational installation, real project binding, hooks/CI, remote publication or Rust implementation was performed.

Artifacts: [findings](findings-ledger.md), [BA/BAT mapping](traceability-matrix.md), [complete specification mapping](complete-spec-traceability.json), [source review](source-review.md), [exact commands](command-log.json), [evidence index](evidence-index.json), [final readback receipt](final-readback-receipt.json). The final receipt records byte preservation and the precise evidence-index exclusions; it is an audit receipt, not framework acceptance.
'''
    save('qa-report.md',report)
    print(json.dumps({'findings':len(FINDINGS),'BA':len(ba),'BAT':counts,'subcases':subcounts,'complete_spec_entries':len(clause),'line_coverage':line_pct,'branch_coverage':branch_pct},indent=2))

if __name__=='__main__':main()
