import datetime, json
from bootstrap import ROOT, PROJECT, write, digest

now=datetime.datetime.now(datetime.timezone.utc).isoformat()
sources=[]
for ident,file,url,sections in [
 ('openai-skills','openai-build-skills.md','https://learn.chatgpt.com/docs/build-skills',['Build skills','How ChatGPT and Codex use skills','Optional metadata','Best practices']),
 ('agent-skills','agentskills-specification-retrieval.json','https://agentskills.io/specification',['Directory structure','Frontmatter','name field','Optional directories','Progressive disclosure']),
 ('openai-prompt','prompt-engineering-live.md','https://developers.openai.com/api/docs/guides/prompt-engineering',['Prompt engineering']),
 ('openai-model','model-guidance-live.md','https://developers.openai.com/api/docs/guides/latest-model/gpt-6-astra',['Prompting best practices','Initiative and follow-through','Instruction following']),
 ('openai-citations','citation-formatting-live.md','https://developers.openai.com/api/docs/guides/citation-formatting',['Choose citable units','Citation Formatting'])]:
    p=ROOT/'guidance'/file
    sources.append({'source_id':ident,'url':url,'retrieved_at_utc':now,'sha256':digest(p.read_bytes()),'snapshot_path':'guidance/'+file,'sections':sections,'freshness':'live_verified','representation':'documentation connector Markdown' if ident!='agent-skills' else 'web extracted page and retrieval metadata, JSON string; not raw HTTP bytes'})
for file in ['prompt-engineering.md','model-guidance.md','citation-formatting.md']:
    b=(PROJECT/'docs/codex'/file).read_bytes(); p=ROOT/'guidance/local'/file; p.parent.mkdir(exist_ok=True); p.write_bytes(b)
    sources.append({'source_id':'local-'+file[:-3],'original_path':str(PROJECT/'docs/codex'/file),'retrieved_at_utc':None,'sha256':digest(b),'snapshot_path':'guidance/local/'+file,'sections':['local historical snapshot'],'freshness':'snapshot_only','limitation':'Original retrieval date unknown; retained for comparison, refreshed live sources govern selected current advice.'})
sources.append({'source_id':'project-spec','original_path':str(PROJECT/'docs/plan/skill-validator-spec.md'),'retrieved_at_utc':now,'sha256':digest((ROOT/'inputs/skill-validator-spec.md').read_bytes()),'snapshot_path':'inputs/skill-validator-spec.md','sections':['4. Requirement register','7. Rules, evidence, and applicability','9. Work-product contracts'],'freshness':'live_verified'})
write(ROOT/'guidance/sources.json',{'schema_version':'1','sources':sources,'retrieval_note':'Official documentation read-only refresh; exact fetched representations retained; no dependencies installed.'})
byid={s['source_id']:s for s in sources}
def ref(sid,section):
    s=byid[sid]; return {'source_id':sid,'url':s.get('url'),'original_path':s.get('original_path'),'sha256':s['sha256'],'locator':{'section':section},'retained_build_snapshot':s['snapshot_path']}
rules=[]
def add(id,title,sid,section,authority,method,required,expected,limitation='',app='applicable'):
    rules.append({'rule_id':id,'revision':'1','title':title,'source_refs':[ref(sid,section)],'authority_class':authority,'applicability':app,'method':method,'expected_observation':expected,'required':required,'limitation':limitation or 'Bounded development observation; no framework acceptance.'})
add('FMT-001','Required entry file and metadata','openai-skills','Build skills','format_requirement','deterministic',True,'SKILL.md exists with YAML name and description; optional folders are not demanded.')
add('FMT-002','Name and description constraints','agent-skills','Frontmatter; name field; description field','format_requirement','deterministic',True,'Name and description are nonempty strings within published limits; applicable naming syntax and directory identity agree.','Source wording about unicode lowercase alphanumeric and parent-directory identity requires scoped interpretation for renamed snapshots; compare original root, not snapshot folder.')
add('FMT-003','Supported optional field types','agent-skills','Frontmatter; compatibility field; metadata field','format_requirement','deterministic',True,'Optional compatibility, metadata, license and allowed-tools preserve published types and applicable constraints.','Host extensions and experimental allowed-tools support require applicability review; installed checker omits compatibility.')
add('FMT-004','Optional host configuration','openai-skills','Optional metadata','official_recommendation','semantic',False,'Existing openai.yaml uses actual supported policy/tool interfaces; absent optional file is not a defect.','Do not enforce sample keys as required; explicit invocation differs from automatic discovery.')
add('REC-001','Focused triggers and routing','openai-skills','How ChatGPT and Codex use skills; Best practices','official_recommendation','behavioral',False,'Positive and near-miss prompts classify with stated scope; report classification separately from native invocation.')
add('REC-002','Progressive disclosure','openai-skills','Build skills; Best practices','official_recommendation','semantic',False,'Essential decisions are reachable from entrypoint; conditional details are linked and loaded when needed.','No universal skill line/token cap; recommendations do not mandate standard folders.')
add('REC-003','Explicit workflow inputs and outputs','openai-skills','Best practices','official_recommendation','semantic',False,'Instructions make the intended result and step inputs/outputs understandable.')
add('PRJ-001','Origin and exact preservation','project-spec','6. Origin, recovery, and provenance','project_policy','deterministic',True,'Snapshot exact bytes, distinguish history, resolve origin before conformance and retain source readback.')
add('PRJ-002','Resources and workflow completeness','project-spec','5. Cohesive workflow; 7. Required assessment families','project_policy','semantic',True,'Every relevant path has produced inputs, reachable transitions, a terminal user outcome and bounded recovery; resource targets resolve.','Markdown parser coverage is bounded; manually inspect unsupported syntax.')
add('PRJ-003','Instruction consistency and ceremonial context','project-spec','7. SV-007: ceremonial and enforcement review','project_policy','semantic',True,'Inspect examples, schemas and contextual control claims; retain useful safeguards and explicit review boundaries.')
add('PRJ-004','Bounded behavior and honest limitations','project-spec','8. Bounded trials and interruption','project_policy','behavioral',True,'Preplan expected behavior, inspect commands, execute authorized disposable cases and retain effects, errors, timeouts and NOT_RUN.')
add('PRJ-005','Evidence identity and status accounting','project-spec','9. Work-product contracts','project_policy','deterministic',True,'References bind real bytes; JSON rejects duplicates/nonfinite; full finding identities and coverage/status reductions are coherent.')
add('PRJ-006','Review before repair and revalidation','project-spec','10. Builder handoff and revalidation','project_policy','semantic',True,'Proposal is complete or explicit about missing decisions; never invoke builder or reuse changed-byte approval; baseline/adoption prerequisites stay separate.')
add('REC-004','Grounded prompt structure and examples','openai-prompt','Prompt engineering','official_recommendation','semantic',False,'Use relevant context and consistent representative examples when applicable.','API guidance applies only to API-backed components; no fixed model or API parameters imposed.', 'unknown')
add('REC-005','Model-specific follow-through','openai-model','Initiative and follow-through; Instruction following','official_recommendation','semantic',False,'Use relevant current-host guidance to honor user intent and avoid repeated approval rituals.','Model-specific tuning is conditional on the identified host/model; not a mandatory model selection.', 'unknown')
add('REC-006','Citation identity and support','openai-citations','Choose citable units','official_recommendation','semantic',False,'Cite stable observed sources with precise supporting locators.','Syntax does not prove support; special citation renderers are not required for Markdown reports.')
write(ROOT/'candidate/assets/rules-snapshot.json',{'schema_version':'1','revision':'2026-09-12.1','compiled_at_utc':now,'freshness':'snapshot_only','fallback_limitation':'Dated summarized catalog. Original fetched representations and digests retained in external build evidence; refresh and save relevant original passages for each new run. This file alone cannot substantiate unseen source text or current-live coverage.','sources':sources,'rules':rules})
print(json.dumps({'sources':len(sources),'rules':len(rules),'freshness':'live sources retained; bundled catalog is dated fallback'}))
