"""V16 labeled validator self-review over actual delivered development bytes."""
import datetime, json, sys
from bootstrap import ROOT, PROJECT, write, digest, inventory
from verification import execute, reference

target=PROJECT/'src/agents/skills/skill-validator'; helper=target/'scripts/observe.py'; A=ROOT/'self-review/20260912T161000Z'
write(ROOT/'self-review/plan.json',{'case_id':'V16','executor':'root author using delivered skill-validator','review_kind':'self_review','target':str(target),'target_before':inventory(target),'specification':reference(ROOT/'inputs/skill-validator-spec.md'),'expected':'Same criteria, outside evidence, no claim of independent self-verification','checks_planned':['format','origin','resource links','workflow contract','instruction/ceremony','helper trials','routing classification','readback','records'],'native_invocation':'NOT_RUN'})
code,p=execute('self-snapshot',[sys.executable,'-B','-X','utf8',helper,'snapshot','--source',target,'--output',A]); assert code==0
(A/'inputs').mkdir(); (A/'observations').mkdir(); (A/'trials').mkdir()
for src,name in [(ROOT/'inputs/skill-validator-spec.md','spec.md'),(ROOT/'helper-tests/helper-observation.json','helper-observation.json'),(ROOT/'routing/attempt-001/observed.json','routing-observed.json'),(ROOT/'boundary-trials/attempt-001/V12-recovery.json','timeout-recovery.json')]: (A/'inputs'/name).write_bytes(src.read_bytes())
for file in ['openai-build-skills.md','agentskills-specification-retrieval.json']:
    (A/'inputs'/file).write_bytes((ROOT/'guidance'/file).read_bytes())
def ref(path): return reference(A/path,A)
manifest=json.loads((A/'source-manifest.json').read_text())
write(A/'origin-record.json',{'schema_version':'1','run_id':'V16','target_name':'skill-validator','original_source_root':str(target),'manifest':ref('source-manifest.json'),'specification':ref('inputs/spec.md'),'origin_kind':'existing_spec','history_kind':'observed','historical_origin':'current authorized build, successful provenance publication still pending','prior_evidence':None,'completeness':'complete','uncertainties':[],'source_readback_state':'NOT_RUN'})
sources=[{'source_id':'approved-spec','snapshot_path':'inputs/spec.md','sha256':ref('inputs/spec.md')['sha256'],'retrieved_at_utc':None,'freshness':'snapshot_only','sections':['1-12']},{'source_id':'openai-skills','snapshot_path':'inputs/openai-build-skills.md','sha256':ref('inputs/openai-build-skills.md')['sha256'],'retrieved_at_utc':'2026-09-12T15:50:29Z','freshness':'live_verified','sections':['Build skills','Best practices']},{'source_id':'agent-skills','snapshot_path':'inputs/agentskills-specification-retrieval.json','sha256':ref('inputs/agentskills-specification-retrieval.json')['sha256'],'retrieved_at_utc':'2026-09-12T15:53:00Z','freshness':'live_verified','sections':['Frontmatter']}]
write(A/'sources.json',{'schema_version':'1','run_id':'V16','target_name':'skill-validator','sources':sources,'limitation':'Live extraction was actually retrieved earlier in this same build; timestamps identify session observation, not upstream publication.'})
plans=[('format','FMT-001','standards','deterministic',True,'Entry metadata and supported resources satisfy pinned selected format.'),('origin','PRJ-001','workflow','semantic',True,'Explicit spec governs, snapshots preserve exact bytes and history is honest.'),('workflow','PRJ-002','workflow','semantic',True,'All actual entrypoint stages have inputs, outputs and explicit continuation/failure/review routes.'),('instructions','PRJ-003','instructions','semantic',True,'Schema names, helper commands, examples and review boundary agree; no self-score or enforcement claim.'),('helper','PRJ-004','behavior','behavioral',True,'Independent helper tests execute success and malformed/unsafe boundary cases.'),('routing','REC-001','behavior','behavioral',False,'Twelve independent description classifications match planned scope; native invocation separate.'),('native-invocation','REC-001','behavior','behavioral',False,'No native discovery selection observed; explicit loading is not implicit activation.')]
rules=[]
for rule in sorted(set(p[1] for p in plans)):
    related=[p for p in plans if p[1]==rule]; source='inputs/openai-build-skills.md' if rule.startswith(('FMT','REC')) else 'inputs/spec.md'; sid='openai-skills' if source.endswith('openai-build-skills.md') else 'approved-spec'
    rules.append({'rule_id':rule,'revision':'1','title':rule,'source_refs':[dict(ref(source),source_id=sid,locator={'section':'Build skills' if sid=='openai-skills' else '4-12'})],'authority_class':'format_requirement' if rule.startswith('FMT') else ('official_recommendation' if rule.startswith('REC') else 'project_policy'),'applicability':'applicable','method':related[0][3],'expected_observation':related[0][5],'required':any(p[4] for p in related),'limitation':'Bounded self-review; no framework authority.'})
write(A/'rule-set.json',{'schema_version':'1','run_id':'V16','target_name':'skill-validator','rules':rules})
write(A/'trials/plan.json',{'schema_version':'1','checks':[{'check_id':p[0],'rule_id':p[1],'dimension':p[2],'method':p[3],'required':p[4],'expected':p[5]} for p in plans],'bound_prior_trials':['inputs/helper-observation.json','inputs/routing-observed.json'],'review_kind':'self_review'})
code,p=execute('self-structure',[sys.executable,'-B','-X','utf8',helper,'structure','--source',A/'source']); assert code==0
(A/'observations/structure.json').write_bytes((p/'stdout.txt').read_bytes())
step_descriptions=[('intake','Intake and boundaries','selected user target/project','identity and disjoint run','origin','missing target ends intake'),('origin','Establish the origin before assessment','target/spec paths','source bytes, manifest, origin record','rules','ambiguity retained while independent checks continue'),('rules','Select rules and inspect','source snapshot and available guidance','pinned rules, checks, workflow map','trials','unsupported source applicability remains unknown'),('trials','Exercise bounded behavior','predeclared fixtures and inspected commands','actual effects and retained attempts','report','timeouts retained; no unsafe execution'),('report','Synthesize and deliver for review','observations and sources','findings, report, full proposal if justified','handoff','input drift requires fresh run'),('handoff','Synthesize and deliver for review','report/proposal readback','review state and exact readiness packet','terminal','stop before builder; missing prerequisite explicit'),('revalidate','Revalidation and recovery','later authorized delivered bytes','resolved/persistent/new/unverified tracking','terminal','fresh run on changed source')]
steps=[]
for ident,entry,inputs,outputs,nxt,failure in step_descriptions:
    steps.append({'step_id':ident,'entrypoint_location':{'path':'source/SKILL.md','section':entry},'entry_conditions':inputs,'inputs':[inputs],'executor':'host agent','action':'Follow cited entrypoint and linked resource contract','outputs':[outputs],'completion_evidence':[ref('source/SKILL.md')],'next_branch_targets':[nxt],'failure_route':failure,'terminal_user_outcome':'Reviewable findings/proposal or concrete retained limitation; target preserved'})
write(A/'workflow-map.json',{'schema_version':'1','run_id':'V16','target_name':'skill-validator','steps':steps})
reason={
 'format':('PASS','Actual structure command exits 0; name/description and all supported inline resources resolve.', ['observations/structure.json']),
 'origin':('PASS','Entrypoint and origin reference resolve explicit/missing/ambiguous spec distinctly; snapshot captures every current file; generated history is not asserted before publication.', ['origin-record.json','source/references/origin.md']),
 'workflow':('PASS','Mapped stages give source/rules/check/trial/report/handoff inputs and outputs; every branch either continues independent checks, retains a concrete limitation or stops at review. Revalidation is a fresh later invocation.', ['workflow-map.json','source/references/handoff.md']),
 'instructions':('PASS','Readback extracts manifest object, finding aliases and dimensions align with helper; instructions retain real approval boundaries and do not claim Python enforcement. Optional metadata is not forced.', ['source/SKILL.md','source/references/reporting.md','source/references/rules.md']),
 'helper':('PASS','Independent 34-test/62-command suite observed real success and rejection behavior and matches delivered helper/test hashes.', ['inputs/helper-observation.json']),
 'routing':('PASS','Independent observed classification matches all 12 original expectations; description byte-equivalent to delivered frontmatter.', ['inputs/routing-observed.json']),
 'native-invocation':('NOT_RUN','Host explicitly loaded skill; no discovery-based activation observation was made.', [])}
checks=[]
for ident,rule,dim,method,required,expected in plans:
    outcome,why,evidence=reason[ident]
    checks.append({'schema_version':'1','run_id':'V16','check_id':ident,'rule_id':rule,'subject_path':'SKILL.md','dimension':dim,'method':method,'required':required,'applicability':'applicable','result':outcome,'reason':why,'evidence':[ref(path) for path in evidence]})
(A/'checks.jsonl').write_text(''.join(json.dumps(c)+'\n' for c in checks),encoding='utf-8')
write(A/'findings.json',{'schema_version':'1','run_id':'V16','target_name':'skill-validator','findings':[]})
code,p=execute('self-readback',[sys.executable,'-B','-X','utf8',helper,'readback','--source',target,'--manifest',A/'source-manifest.json']); assert code==0
write(A/'source-after-manifest.json',json.loads((p/'stdout.txt').read_text())['manifest'])
origin=json.loads((A/'origin-record.json').read_text()); origin['source_readback_state']='UNCHANGED'; write(A/'origin-record.json',origin)
(A/'enforcement-recommendations.md').write_text('# Enforcement recommendations\n\nNo implementation candidates selected by this self-review. Existing review-before-repair and bounded evidence instructions remain guidance_only. Future protected provenance, mutation authority or host event integration belongs to a separately authorized compiled-Rust/enforcement design; this package claims none.\n',encoding='utf-8')
(A/'validation-report.md').write_text('# Validator self-review (V16)\n\nReview kind: **self-review by the build author**, not independent verification. Assessment completed: true. Outcome PASS for the bounded selected required checks (5/5 evaluated); advisory native implicit invocation NOT_RUN. Package digest `'+manifest['package_digest']+'`; rule-set digest `'+ref('rule-set.json')['sha256']+'`.\n\nStandards, workflow, instruction quality and bounded behavior passed the explicitly recorded checks. Enforcement is a descriptive recommendation dimension, not a gate. The linked workflow-map and checks retain concrete reasons and actual script/classification evidence. A separate independent cold trial already detected an unintended arithmetic defect in its disposable receipt target; that target failure demonstrates exercised validator behavior and is not a defect here. Current target readback is unchanged. No revision proposal is justified by this bounded self-review; readiness NO_CHANGE, review not_needed.\n\nAll applicable mandatory checks in the selected rule-set digest above passed for the package digest above. This is not complete current-standards coverage, independent semantic proof, native implicit activation, protected acceptance, installation or Rust qualification.\n',encoding='utf-8')
(A/'command-log.md').write_text('# Commands\n\nExact commands, streams and readbacks are retained outside the assessed package in the build commands/self-* directories. Self-review plan is ../plan.json. Preceding independent test and routing inputs remain in the original external build evidence; their bound observation copies are inputs here. No target mutation or builder invocation occurred.\n',encoding='utf-8')
write(A/'handoff.json',{'schema_version':'1','run_id':'V16','target_name':'skill-validator','original_target_root':str(target),'original_manifest':ref('source-manifest.json'),'origin':ref('origin-record.json'),'proposed_spec':None,'findings':ref('findings.json'),'report':ref('validation-report.md'),'selected_finding_ids':[],'deferred_finding_ids':[],'proposal_review_state':'not_needed','review_instruction':None,'builder_readiness':'NO_CHANGE','readiness_reasons':['No proposed change in this bounded self-review'],'baseline_kind':None,'baseline_reference':None,'adoption_required':False,'adoption_capability':'not_needed','permitted_target_root':str(target),'preservation_requirements':['all target bytes','existing source specifications and evidence']})
write(A/'assessment.json',{'schema_version':'1','assessment_completed':True,'overall_assessment':'PASS','dimensions':{name:'PASS' for name in ['standards','workflow','instructions','behavior']},'review_kind':'self_review'})
write(ROOT/'self-review/records-input-before.json',inventory(A))
code,p=execute('self-records',[sys.executable,'-B','-X','utf8',helper,'records','--run-root',A]); assert code==0
assert inventory(A)['files']==json.loads((ROOT/'self-review/records-input-before.json').read_text())['files']
write(ROOT/'self-review/final-receipt.json',{'case_id':'V16','review_kind':'self_review','report':reference(A/'validation-report.md'),'record_integrity_exit':code,'target_readback_unchanged':inventory(target)['files']==manifest['files'],'no_independent_self_verification_claim':True})
print(str(A))
